/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_fernandopadilla;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class FrameM extends javax.swing.JFrame {

    /**
     * Creates new form FrameM
     */
    public FrameM() {
        initComponents();
    }

    ArrayList<Vehiculo> carros = new ArrayList();
    ArrayList<Vendedor> vendedores = new ArrayList();
    ArrayList<Cliente> clientes = new ArrayList();

    int idCarro = 0;

    private void inicializaridCarro() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_crearVehiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_modelo = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        btn_color = new javax.swing.JButton();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        btn_crearVehiculo = new javax.swing.JButton();
        panel_crearVendedor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_cantCV = new javax.swing.JTextField();
        tf_dineroG = new javax.swing.JTextField();
        tf_nombreVendedor = new javax.swing.JTextField();
        btn_crearVendedor = new javax.swing.JButton();
        panel_crearCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_profesion = new javax.swing.JTextField();
        btn_crearCliente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tf_cantCC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_sueldo = new javax.swing.JTextField();
        jSpinner_edad = new javax.swing.JSpinner();
        panel_asignarV = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        panel_crearVehiculo.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Marca");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Color");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Modelo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Año");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Precio");

        btn_color.setForeground(new java.awt.Color(0, 0, 0));
        btn_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_colorMouseClicked(evt);
            }
        });

        btn_crearVehiculo.setText("Crear");
        btn_crearVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearVehiculoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_crearVehiculoLayout = new javax.swing.GroupLayout(panel_crearVehiculo);
        panel_crearVehiculo.setLayout(panel_crearVehiculoLayout);
        panel_crearVehiculoLayout.setHorizontalGroup(
            panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_crearVehiculoLayout.createSequentialGroup()
                        .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_modelo)
                                .addComponent(tf_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(tf_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(btn_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 372, Short.MAX_VALUE))
                    .addComponent(btn_crearVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_crearVehiculoLayout.setVerticalGroup(
            panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearVehiculoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_crearVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btn_crearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Vehiculo", panel_crearVehiculo);

        panel_crearVendedor.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cantidad de Carros Vendidos");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad de Dinero Generado");

        btn_crearVendedor.setText("Agregar");
        btn_crearVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearVendedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_crearVendedorLayout = new javax.swing.GroupLayout(panel_crearVendedor);
        panel_crearVendedor.setLayout(panel_crearVendedorLayout);
        panel_crearVendedorLayout.setHorizontalGroup(
            panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crearVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_crearVendedorLayout.createSequentialGroup()
                        .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(panel_crearVendedorLayout.createSequentialGroup()
                                .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_crearVendedorLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_dineroG, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_crearVendedorLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_nombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_cantCV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_crearVendedorLayout.setVerticalGroup(
            panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearVendedorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_cantCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_crearVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_dineroG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(btn_crearVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Vendedor", panel_crearVendedor);

        panel_crearCliente.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Profesion");

        btn_crearCliente.setText("Agregar");
        btn_crearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearClienteMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Cant. Carros Comprados");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Sueldo Disp.");

        jSpinner_edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        javax.swing.GroupLayout panel_crearClienteLayout = new javax.swing.GroupLayout(panel_crearCliente);
        panel_crearCliente.setLayout(panel_crearClienteLayout);
        panel_crearClienteLayout.setHorizontalGroup(
            panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_crearClienteLayout.createSequentialGroup()
                        .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_crearClienteLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_crearClienteLayout.createSequentialGroup()
                                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_crearClienteLayout.createSequentialGroup()
                                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_cantCC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_crearClienteLayout.setVerticalGroup(
            panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearClienteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_cantCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btn_crearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Cliente", panel_crearCliente);

        panel_asignarV.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panel_asignarVLayout = new javax.swing.GroupLayout(panel_asignarV);
        panel_asignarV.setLayout(panel_asignarVLayout);
        panel_asignarVLayout.setHorizontalGroup(
            panel_asignarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        panel_asignarVLayout.setVerticalGroup(
            panel_asignarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Asignar Venta", panel_asignarV);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_colorMouseClicked
        // TODO add your handling code here:
        btn_color.setBackground(JColorChooser.showDialog(this, "Escoger un color", Color.yellow));
    }//GEN-LAST:event_btn_colorMouseClicked

    private void btn_crearVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearVehiculoMouseClicked
        // TODO add your handling code here:
        if (tf_marca.getText().isEmpty() || tf_modelo.getText().isEmpty() || tf_precio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los parametros deben estar completos");
        } else {
            String marca = tf_marca.getText();
            Color color = btn_color.getBackground();
            String modelo = tf_modelo.getText();
            int ft = jYearChooser1.getYear();
            String año = String.valueOf(ft);
            double precioV = Double.parseDouble(tf_precio.getText());
            carros.add(new Vehiculo(marca, color, modelo, año, precioV, idCarro));
            idCarro++;
            File file = null;
            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                file = new File("./Carros.txt");
                fw = new FileWriter(file, true);
                bw = new BufferedWriter(fw);
                String lineas = "[\n"
                        + "\t" + marca + ",\n"
                        + "\t" + modelo + ",\n"
                        + "\t" + año + ",\n"
                        + "\t" + precioV + "\n]\n";
                bw.write(lineas);
                bw.flush();
                fw.close();
                bw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Agregado exitosamente");
            tf_marca.setText("");
            tf_modelo.setText("");
            tf_precio.setText("");
            btn_color.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_crearVehiculoMouseClicked

    private void btn_crearVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearVendedorMouseClicked
        // TODO add your handling code here:
        if (tf_nombreVendedor.getText().isEmpty() || tf_cantCC.getText().isEmpty() || tf_dineroG.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los parametros deben estar llenos");
        } else {
            String nombre = tf_nombreVendedor.getText();
            int cantCV = Integer.parseInt(tf_cantCC.getText());
            double cantDG = Double.parseDouble(tf_dineroG.getText());
            vendedores.add(new Vendedor(nombre, cantCV, cantDG));
            File file = null;
            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                file = new File("./Vendedores.txt");
                fw = new FileWriter(file, true);
                bw = new BufferedWriter(fw);
                String lineas = "[\n"
                        + "\t" + nombre + ",\n"
                        + "\t" + cantCV + ",\n"
                        + "\t" + cantDG + "\n]\n";
                bw.write(lineas);
                bw.flush();
                fw.close();
                bw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Agregado exitosamente");
        }
    }//GEN-LAST:event_btn_crearVendedorMouseClicked

    private void btn_crearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearClienteMouseClicked
        // TODO add your handling code here:
        String nombre = tf_nombreCliente.getText();
        int edad = (int) jSpinner_edad.getValue();
        String profesion = tf_profesion.getText();
        int cantCC = Integer.parseInt(tf_cantCC.getText());
        double sueldoD = Double.parseDouble(tf_sueldo.getText());
        clientes.add(new Cliente(nombre, edad, profesion, cantCC, sueldoD));
        File file = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            file = new File("./Clientes.txt");
            fw = new FileWriter(file, true);
            bw = new BufferedWriter(fw);
            String lineas = "[\n"
                    + "\t" + nombre + ",\n"
                    + "\t" + edad + ",\n"
                    + "\t" + profesion + ",\n"
                    + "\t" + cantCC + ",\n"
                    + "\t" + sueldoD + "\n]\n";
            bw.write(lineas);
            bw.flush();
            fw.close();
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "Agregado exitosamente");

    }//GEN-LAST:event_btn_crearClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_color;
    private javax.swing.JButton btn_crearCliente;
    private javax.swing.JButton btn_crearVehiculo;
    private javax.swing.JButton btn_crearVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner_edad;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JPanel panel_asignarV;
    private javax.swing.JPanel panel_crearCliente;
    private javax.swing.JPanel panel_crearVehiculo;
    private javax.swing.JPanel panel_crearVendedor;
    private javax.swing.JTextField tf_cantCC;
    private javax.swing.JTextField tf_cantCV;
    private javax.swing.JTextField tf_dineroG;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JTextField tf_nombreCliente;
    private javax.swing.JTextField tf_nombreVendedor;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_profesion;
    private javax.swing.JTextField tf_sueldo;
    // End of variables declaration//GEN-END:variables
}
